name: ExtDN M2 Integration Tests
on: [ push, pull_request ]

jobs:
  integration:
    uses: customgento/m2-github-actions/.github/workflows/integration.yml@main
    with:
      module_name: CustomGento_CliTaxEditor
      composer_name: customgento/module-cli-tax-editor-m2
