name: ExtDN M2 PHPStan
on: [push, pull_request]

jobs:
  phpstan:
    name: M2 PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: waleedbasit/github-actions-m2/magento-phpstan@add-elasticsearch7-to-install-config
        with:
          composer_name: customgento/module-cli-tax-editor-m2
